version: '3'
services:
  postgres:
    image: postgres:12.7-alpine
    container_name: postgres
    ports:
      - 5433:5432
    volumes:
      - ./postgres/init:/tmp/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    hostname: postgres
    restart: always
    user: root
